### ISSUE TITLE
Arguments Missing When Inheriting from Server Class

### ISSUE THREAD

**Issue by citruspi** [hudl/Tyr#117]
While doing a code review for #115 I realized that the arguments

- `ingress_groups_to_add`
- `ports_to_authorize`
- `classic_link`
- `add_route53_dns`

in the `Server` class weren't being exposed in many of the inheriting classes.

**Comment by Z3r0Sum** [comment]
I can add those into #115 if you'd like?

**Comment by citruspi** [comment]
I'd absolutely love that.

**Comment by Z3r0Sum** [comment]
I'll knock it out tomorrow
