### ISSUE TITLE
Mongo Router Class

### ISSUE THREAD

**Issue by Z3r0Sum** [hudl/Tyr#118]
Need a router class such that the instance name and corresponding route53 records get created correctly.  Additionally, this would serve as a way to not create unnecessary EBS volumes and set the appropriate attributes, if any, for a router.

Will need to adjust https://github.com/hudl/role_mongo default attributes for EBS to account for the router type.

This should also include proper tags - i.g. `RoleMongoRouter` for the Role.

**Comment by citruspi** [comment]
Implemented in #146.
