### ISSUE TITLE
Update Route53 record if it exists

### ISSUE THREAD

**Issue by atharvai** [hudl/Tyr#140]
I've found every time I run `autorun()` to create a node, it will fail for some reason. I will then terminate the node in EC2 and rerun `autorun()` . This of course doesn't delete the Route53 record so next time Tyr will error out saying CName record already exists. Probably because it creates a new node with same name. (restarting from 01). 

Tyr should update the CNAME record if it exists instead of crashing.

**Comment by citruspi** [comment]
FWIW if you do
```
n = Server(...)
n.autorun()
```
and it fails and you decide to terminate it, you can just run
```
n.terminate()
```
without having to go to the AWS Console.

As for the Route53 stuff, Tyr no longer handles Route53 stuff (#145). That is now handled by Chef (https://github.com/hudl/role_base/pull/32). If an overlapping record exists, then Chef will update the DNS record with the new value _if_ the existing record is the same type as the new one. (Over time, we have changed the DNS records we setup and their types, so there's some old, inconsistent, unused records out there).

In your case, an instance failing to start, terminating it, and immediately relaunching another one, the DNS records should be of the same type so it should just update the records for you.
