### ISSUE TITLE
EC2 Instance Tag With Replica Set Information

### ISSUE THREAD

**Issue by citruspi** [hudl/Tyr#22]
@jamiegs mentioned that we should have an EC2 instance tag on MongoDB nodes which would contain something like `MONOLITH-RS1`. If I remember correctly, this would be used when backing up MongoDB databases.

I'm not sure what the tag name would be. Probably `ReplicaSet`?

**Comment by jamiegs** [comment]
yeah, I've started using tag ```ReplicaSet``` already. I'm having the value be all lowercase also.

Monolith would actually just be rs1, rs2, rs3, etc. It has to match the actual name of the mongo ReplicaSet name value.

Primarily this is going to be used for backup purposes. Because the snapshots are named based on the replicaset name, I want to have an easy way to know the name from the outside of the server so we can easily check when the most recent backup for that cluster is and alert if it hasn't been backed up.

**Comment by citruspi** [comment]
> Monolith would actually just be rs1, rs2, rs3, etc. It has to match the actual name of the mongo ReplicaSet name value.

So [the replica set template currently used][0] is `{group}-rs{set_}`.

The only time that an existing replica set name that _does not_ match the hard coded template is used is in the [`replace_mongo_server`][1] module where it SSH's into the replica set and determines the existing set name.

How would it work spinning up new nodes? I can think of a few ideas.

1. The users' manually determine the replica set name and just set the variable.

    ```python
    from tyr.servers.mongo import MongoDataNode

    n = MongoDataNode(group='monolith')
    n.REPLICA_SET_TEMPLATE = 'rs1'
    n.autorun()
    ```

2. The users' manually determine the replica set name and an argument exists for passing it in. If it is not passed it, is uses the predefined replica set name template.

    ```python
    from tyr.servers.mongo import MongoDataNode

    n = MongoDataNode(group='monolith', replica_set_template='rs1')
    n.autorun()
    ```

3. The users' know of an existing member in the replica set and pass that in. The existing member is used to determine the replica set name which is then used. If it is not passed it, is uses the predefined replica set name template.

    ```python
    from tyr.servers.mongo import MongoDataNode

    n = MongoDataNode(group='monolith', follow='s-monolith-mongo-c-02')
    n.autorun()
    ```

4. So, this one is a little more complicated than the previous ones, but it allows the use of existing replica set names which don't match the template _without_ any additional work by the users. If the user doesn't pass in an argument with a replica set name or an existing member, then instead of falling back to using the `REPLICA_SET_TEMPLATE` value, we could use the replica set (number), group, environment, etc. to search EC2 for existing members. If one is found, we use the replica set name value found on that node, if not fall back to `REPLICA_SET_TEMPLATE`.

    ```python
    from tyr.servers.mongo import MongoDataNode

    n = MongoDataNode(group='monolith')
    n.autorun()
    ```

[0]: https://github.com/hudl/Tyr/blob/master/tyr/servers/mongo/member.py#L5
[1]: https://github.com/hudl/Tyr/blob/master/tyr/utilities/replace_mongo_server.py#L624
