### ISSUE TITLE
Mongo server replacement appears to be forwarding DNS cname to public address

### ISSUE THREAD

**Issue by malkolm** [hudl/Tyr#42]
I think the cname update that is part of the mongo server replacement updates the existing dns recored to point to the public dns name of the new mongo server.  If this server is in the VPC, it will be inaccessible to nodes in EC2 classic.  I believe this cname update should point to the internal dns name.

`zone.update_cname(member+'.', node.instance.public_dns_name)`

**Comment by citruspi** [comment]
That definitely makes sense. I'm about to board my flight, would you be able to take this?

**Comment by malkolm** [comment]
I'll try to get to it later today.

**Comment by citruspi** [comment]
Great. I know @jamiegs wanted to start the server replacements in the afternoon so they could sync and the only work required in the morning would be the cleanup. 

Ping him when it's done and I'll try to do a code review later.

**Comment by citruspi** [comment]
This issue was fixed in 15b4eec.
