### ISSUE TITLE
Tagging EBS volumes

### ISSUE THREAD

**Issue by agilejon** [hudl/Tyr#82]
It would be awesome if we could tag our EBS volumes with data like the name of the instance it's attached to (or, maybe was attached to upon creation).

It would be nice to be able to filter and analyze our volumes by the same tags as our instances.

**Comment by citruspi** [comment]
I've implemented this in https://github.com/hudl/role_base/pull/33. I included both the instance name and ID for 

> data like the name of the instance it's attached to (or, maybe was attached to upon creation)

I'm not sure if you still need/want that data available via the EBS volume tags, I can remove it before merging if not. Feel free to weigh in over there if you feel there are any tags missing.
